---
  - name: Create /var/www/magento-ce and and change permissions
    file: path=/var/www/magento-ce mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-ee
    file: path=/var/www/magento-ee mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-ee/magento2ce
    file: path=/var/www/magento-ee/magento2ce mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-ee/magento2ee
    file: path=/var/www/magento-ee/magento2ee mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-b2b
    file: path=/var/www/magento-b2b mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-b2b/magento2ce
    file: path=/var/www/magento-b2b/magento2ce mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-b2b/magento2ee
    file: path=/var/www/magento-b2b/magento2ee mode=0777 state=directory owner=vagrant group=vagrant
  - name: Create /var/www/magento-b2b/magento2b2b
    file: path=/var/www/magento-b2b/magento2b2b mode=0777 state=directory owner=vagrant group=vagrant
