---
  - name: Create /var/www/magento-ce and and change permissions
    file: path=/var/www/magento-ce mode=0777 state=directory
  - name: Create /var/www/magento-ee
    file: path=/var/www/magento-ee mode=0777 state=directory
  - name: Create /var/www/magento-tests
    file: path=/var/www/magento-tests mode=0777 state=directory
  - name: Copy unit tests script
    copy: src=run-unit.sh dest=/var/www/magento-tests/run-unit.sh
  - name: Copy static tests script
    copy: src=run-static.sh dest=/var/www/magento-tests/run-static.sh
  - name: Copy integration tests script
    copy: src=run-static.sh dest=/var/www/magento-tests/run-integration.sh